\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{eecslides}[17/07/2016, v0.2]

\LoadClass[professionalfonts,10pt]{beamer}

\RequirePackage[utf8]{inputenc} % encodage UTF-8
\RequirePackage[OT1]{fontenc} % encodage de la police de caracteres

\RequirePackage[absolute,overlay]{textpos}

%\RequirePackage[charter]{mathdesign}
%\RequirePackage{berasans}
%\RequirePackage[scaled]{beramono}

\RequirePackage[default,scale=0.9]{droidserif}
\RequirePackage[defaultsans,scale=0.9]{droidsans}
\RequirePackage[defaultmono,scale=0.9]{droidmono}
\RequirePackage[LGRgreek]{mathastext}

\usetheme{KevCaz}
\usecolortheme{KevCaz}

\RequirePackage{pgfcb}
